### ISSUE TITLE
Multiple native modules failure

### ISSUE THREAD

**Issue by arcanis** [charto/nbind#60] opened 2017-01-09 16:48 UTC
I think this issue is similar to #30 (so much that I actually copied the title :p), but the symptoms are a bit different (and quite harder to spot). It seems that if two nbind modules are loaded, the second one will not be correctly binded, and will not convert the binded structures.

The only workaround I found is to use the asmjs fallbacks.

**[edit]** After more tries, it seems it might get worse and we might also get "Type mismatch" errors in some cases. For example, if you do the following:

```
$> npm install @manaflair/text-layout
$> cp -rf node_modules/@manaflair node_modules/@test
```

Then run this code:

```js
let TextLayoutA = require(`@manaflair/text-layout`).TextLayout;
let TextLayoutB = require(`@test/text-layout`).TextLayout;

for (let TextLayout of [ TextLayoutA, TextLayoutB ]) {

    let textLayout = new TextLayout();

    textLayout.setCharacterGetter(() => `?`);
    textLayout.setCharacterCountGetter(() => 0);

    console.assert(textLayout.reset().apply);

}
```

The execution will fail (instead of passing twice).

**Comment by jjrv** [comment] 2017-01-13 15:42
Can you test if the latest `develop` branch fixes your issue?

It seems that when Node.js does `dlopen(filename, RTLD_LAZY);` then symbols with matching names from different addons get mapped to the same memory address, at least in some cases. So your second `require` ended up partially reinitializing exports from the first `require` and messing up their inheritance chain. Such reinitialization is now prevented.

**Comment by arcanis** [comment] 2017-01-18 19:44
Hm I've checked but I didn't see any change. However, I'm not completely sure I correctly updated all the dependencies nbind dependencies :/

**Comment by arcanis** [comment] 2017-01-18 19:49
Isn't the issue triggered because `require('nbind')` would resolve to the same instance of the 'nbind' module if they share the same version?

**Comment by arcanis** [comment] 2017-01-18 19:57
I've made a test with the snippet above, and got the following error:

```
module.js:598
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: Module did not self-register.
    at Object.Module._extensions..node (module.js:598:18)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at initNode (/tmp/bar/node_modules/b/node_modules/nbind/dist/nbind.js:140:15)
    at /tmp/bar/node_modules/b/node_modules/nbind/dist/nbind.js:114:13
    at findCompiledModule (/tmp/bar/node_modules/b/node_modules/nbind/dist/nbind.js:78:13)
    at find (/tmp/bar/node_modules/b/node_modules/nbind/dist/nbind.js:92:13)
```

**Comment by jjrv** [comment] 2017-01-19 13:01
`require('nbind')` doesn't really do anything. `nbind.init` receives the `__dirname` from the requiring module, so it should load a different compiled file from `@manaflair/text-layout` and `@test/text-layout`. With the latest release (0.3.9 published just now) the snippet works for me. Maybe try again with that version, in case there was an incorrect reference from the test modules to the `develop` version earlier?

**Comment by arcanis** [comment] 2017-01-19 20:35
Nope, no luck :( Does the following script works for you?

```sh
#!/usr/bin/env bash

mkdir -p /tmp/$$/
cd /tmp/$$/

npm install @manaflair/text-layout

mkdir -p node_modules/a
mkdir -p node_modules/b

sudo mount --bind node_modules/@manaflair/text-layout node_modules/a
sudo mount --bind node_modules/@manaflair/text-layout node_modules/b

node <<EOF

let TextLayoutA = require("a").TextLayout;
let TextLayoutB = require("b").TextLayout;

for (let TextLayout of [ TextLayoutA, TextLayoutB ]) {

    let textLayout = new TextLayout();

    textLayout.setCharacterGetter(() => "?");
    textLayout.setCharacterCountGetter(() => 0);

    console.assert(textLayout.reset().apply);

}

EOF

sudo umount node_modules/a
sudo umount node_modules/b
```

**Comment by arcanis** [comment] 2017-01-19 20:48
(I've updated the script to use less schenanigans, since I think it was yielding the wrong error)

**Comment by jjrv** [comment] 2017-01-20 09:25
It seems the issue is how templates are handled with dynamic linking. If two addons have identically named classes, nbind defines template specializations like `BindDefiner<Patch>` and `BindClass<Patch>` in both of them. Then in each case one specialization ends up overriding the other due to matching template arguments, even though only the names of the classes are equal!

I'll probably have to pass the npm package name to the C++ compiler, to use as a unique identifier disambiguating between addons.

**Comment by jjrv** [comment] 2017-01-20 11:12
This will probably be fixed in 0.4.0. It's going to be a breaking change in the sense that you need to re-run a newer version of autogypi to make the next nbind version compile.

**Comment by arcanis** [comment] 2017-02-09 21:11
Hi @jjrv ! Any news about the 0.4.0 ? No hurry, just wondering ^_^

**Comment by jjrv** [comment] 2017-02-10 07:48
I ran into issues with [cbuild](https://github.com/charto/cbuild), [cxml](https://github.com/charto/cxml) and [cxsd](https://github.com/charto/cxsd) in another project, and had to fix those. I can probably resume working on nbind after one week now.

**Comment by arcanis** [comment] 2017-02-26 15:04
I've investigated a bit: the issue isn't limited to conflicting class names. When two nbind-generated modules are loaded, only the first one will work as expected. I've setup a repository so you can easily test it:

https://github.com/arcanis/nbind-native-clash

Clone it, run `./install.sh`, then use the `index.js` script to test the behaviour. Here's what I get:

```
arcanis@DESKTOP-L3PL4FG:~/xxx/a$ node index.js a
A
[Function: log]
[Function: log]
arcanis@DESKTOP-L3PL4FG:~/xxx/a$ node index.js b
B
[Function: log]
[Function: log]
arcanis@DESKTOP-L3PL4FG:~/xxx/a$ node index.js a b
A
[Function: log]
[Function: log]
B
undefined
undefined
arcanis@DESKTOP-L3PL4FG:~/xxx/a$
```

As you can see, both modules work fine individually, but break when used together.

Could it be possible to fix this issue in the 0.3 branch? I can't recommend my modules if it means my users will not be able to use others modules with it :( Using the js builds is a workaround, but it pollutes a bit the codebases and lowers perfs needlessly.

Since calling `lib.init` with `__dirname` as parameter is already required, perhaps fixing this wouldn't require any API change, if you were using this dirname as context name.

**Comment by arcanis** [comment] 2017-04-29 16:17
Ping @jjrv?

**Comment by jjrv** [comment] 2017-05-02 19:46
I need to update `autogypi` for this to work, because the module name must be passed to the C++ compiler as a macro. I'll try to get this done now. Endless deadlines in other projects...

**Comment by arcanis** [comment] 2017-05-02 22:35
Eh eh, don't worry, it currently has a decent workaround :) However, what do you think about my earlier suggestion? Wouldn't using `__dirname` as "module name" be enough? Plus, it would work even with multiple instances of the same module (which might happen if different modules depend on different versions of a same nbind-compiled module).

**Comment by jjrv** [comment] 2017-05-02 22:46
It seems that identically named symbols from different libraries get mapped to the same address when loaded. That means the module name has to go into all symbol names in the compiled binary. Only a macro definition passed to the compiler can do that.

As to multiple versions of an identically named module, Node.js doesn't support that at all. NPM won't install them, and `require` will only load the first one it finds anyway.

**Comment by jjrv** [comment] 2017-05-04 15:24
OK this rabbit hole goes way deeper than I thought. Do you run OS X? Then you really need to try this. Create the files below and run these commands:

```bash
npm install
node index.js
```

It will print something like:

```
0x102dcbe9c
BAZINGA!
```

This is beyond messed up. Certainly not fixable in nbind (not even used here). On Linux it won't print the second line.

`package.json`:

```json
{
  "dependencies": {
    "nan": "^2.6.2",
    "node-expat": "^2.3.15",
    "node-gyp": "^3.6.1"
  }
}
```

`binding.gyp`:

```json
{
	"targets": [{
		"target_name": "bazinga",
		"include_dirs": [
			"node_modules/nan"
		],
		"sources": [ "main.cc" ]
	}]
}
```

`main.cc`:

```C++
#include <nan.h>

struct Parser : public Nan::ObjectWrap {
	static void EndElement(void *userData, const char *name) {
		fprintf(stderr, "BAZINGA!\n");
	}
};

void init(v8::Handle<v8::Object> exports) {
	printf("%p\n", Parser::EndElement);
}

NODE_MODULE(bazinga, init)
```

`index.js`:

```JavaScript
require('./build/Release/bazinga.node');

var parser = new (require('node-expat').Parser)('UTF-8');

parser.write('<a></a>');
```

**Comment by arcanis** [comment] 2017-05-04 16:10
Pretty sure it's because [Node is calling dlopen without specifying any other flag than `RTLD_LAZY`](https://github.com/nodejs/node/blob/db1087c9757c31a82c50a1eba368d8cba95b57d0/deps/uv/src/unix/dl.c#L36), which means that the behavior is up to the system. On OSX it's `RTLD_GLOBAL`, but on Linux it should be `RTLD_LOCAL`. Pretty weird if you ask me ... I wonder if that should be fixed on Node's side. It seems to be such a big oversight :/

**Comment by arcanis** [comment] 2017-05-04 16:25
Maybe a workaround would be to call objcopy on the resulting obj files to prefix them with some pseudo-random string ... cf http://stackoverflow.com/questions/10157680/how-can-i-get-gcc-to-add-a-prefix-to-all-symbol-names

**Comment by jjrv** [comment] 2017-05-04 17:13
It seems to work by adding this to `binding.gyp`:

```json
"OTHER_LDFLAGS": [
  "-exported_symbols_list",
  "/dev/null"
]
```

Not sure if it will break something else...

**Comment by jjrv** [comment] 2017-05-30 04:31
This should now work in the 0.3.12 release.

**Closed by jjrv** 2017-05-30 04:31 UTC

**Comment by arcanis** [comment] 2017-06-01 18:39
Works fine 👍 Note that for Linux, the right flag is `-fvisibility=hidden` (on both CFLAGS and LDFLAGS).
